### ISSUE TITLE
Tooltips are always shown in debug session

### ISSUE THREAD

**Issue by LaraSQP** [VictorLoktev/TameVisualStudioTooltips#1]
I have looked at the code but cannot find where debug sessions are somehow made not to call `GetQuickInfoItemAsync`

Thanks, this extension is a must-have.

**Comment by VictorLoktev** [comment]
Thank you for your interest!

I made some changes and released a new build. I will be glad if you look at the new version.

The following code is used to determine the current VS mode:

dte = Microsoft.VisualStudio.Shell.Package.GetGlobalService( typeof( Microsoft.VisualStudio.Shell.Interop.SDTE ) ) as EnvDTE.DTE;
dbgDebugMode vsState = dte.Debugger.CurrentMode;

Then fork:
            if( vsState == dbgDebugMode.dbgDesignMode && options.ShowTooltipsEdit > 0 ) {}
            if( vsState == dbgDebugMode.dbgBreakMode && options.ShowTooltipsDebug > 0 ) {}

I want make a small notice.
If mouse hovers token in debugger break mode and VS show value of the token, it's not a QuickInfo.
Method GetQuickInfoItemAsync is not called at this time.
If you want disable tooltip with variable value at debug break mode, I beleave there is a option in MSVS.

**Comment by LaraSQP** [comment]
You rock, sir.
